### ISSUE TITLE
[質問] 画像取得不可になる事象について

### ISSUE THREAD

**Issue by denkakka** [seriwb/reins#19]
お世話になります。

画像取得を数週～1か月程度の期間行っていると、特定のディレクトリ（リスト）のみ画像取得不能になる事象が発生します。
お手数をおかけしますが、解決方法について質問させてください。

[影響している内容]
不特定のタイミングで画像取得不能になる。
dbディレクトリを削除し、reinsにより再構成されることで画像取得を再開できるが、過去に取得済みだった画像も再取得される。

[使用方法]
リスト毎、その中にユーザー名毎でのディレクトリが構成され、画像が保存される形での利用をしています。
保存された画像を確認後、ユーザー名のディレクトリごと、もしくはディレクトリ内の画像を削除しています。
削除の際、reinsは起動中もしくは終了いずれの状態もあります。
※なお、タイムラインのディレクトリは構成していません。

[再現手順]
（reins0.3.4導入までを省略）
1.reinsがリスト毎、その中にユーザー名毎にディレクトリを構成
2.reinsが画像を取得
3.画像を参照　※XnViewという画像ビューアを利用、もしくはディレクトリ内をWindowsエクスプローラで参照
4.ユーザー名のディレクトリごと、もしくはディレクトリ内の画像を削除
5.2～4を事象が発生するまで繰り返し実施
6.数週～1か月程度経過時に、特定のディレクトリにおいて画像を取得しなくなる
　※取得し続けられているディレクトリも存在する
7.dbディレクトリを削除し、画像取得再開
　※reinsにてtwitterでの再認証実施

[利用中のconfig値]
// 画像の保存場所
reins.image.dir = "./dir"

// Tweetの1回の取得数（MAX:100）
reins.tweet.maxcount = 100

// 繰り返しのWait間隔ベース（s）：画像取得はこの時間の半分
reins.loop.waittime = 1200

// Retweetの取得（取得する：true/取得しない：false）
reins.retweet.target = true

// Retweetのディレクトリを分離（分離する：true/分離しない：false）
reins.retweet.separate = false

// タイムラインの画像取得（取得する：true/取得しない：false）
reins.timeline.target = false

// リストの画像取得（取得する：true/取得しない：false）
reins.list.target = true

[実行環境]
・OS：Windows10
・reinsバージョン：0.3.4
・記憶媒体：SSD

[備考]
事象がよく発生するディレクトリのリストについて
・ユーザ数は25程度
・tweet数、画像数は正確に計測できていませんが、
　画像取得不可になるまでの総画像取得数は、
　感覚値ですがおおよそ3000点以上は取得していたと思われます。

以上、お手数をおかけしますがよろしくお願い致します。

**Comment by seriwb** [comment]
報告ありがとうございます。

ダウンロード処理は、何をダウンロードするかをリストごとのテーブルに一度保持してから行っているので、
状況から推測するにおそらく対象ディレクトリを管理しているテーブルのレコード数が多くなり、
更新処理時にH2 DBデフォルトのロックタイムアウトの時間を超えて、テーブルの更新処理が失敗したため、ダウンロードも行われていない、という状況なのではないかと思います。

もし可能であれば、お使いのreinsのディレクトリにlogディレクトリがあると思うので、
エラーが発生していたと思われる日時のファイルを"ERROR"

以下に設定を追加し、ビルドし直せば対応できるかと思うので、後ほど修正版をリリースさせて貰います。
https://github.com/seriwb/reins/blob/master/src/main/groovy/box/white/reins/ReinsConstants.groovy

また、お使いのreinsのディレクトリにlogディレクトリがあると思うのですが、

**Comment by denkakka** [comment]
ご確認いただきありがとうございます。

>もし可能であれば、お使いのreinsのディレクトリにlogディレクトリがあると思うので、
>エラーが発生していたと思われる日時のファイルをERRORの文字列で検索をかけていただき、
>DatabaseエラーやTimeoutのようなものがないかをチェックいただけると助かります。
→発生当日およびその5日前までのログをERRORの文字列で検索してみましたが、該当なしでした。

>問題の対策としては、以下に設定を追加し、ビルドし直せば対応できるかと思うので、後ほど修正版をリリースさせて貰います。
→ありがとうございます。リリースを待って試したいと思います。

**Comment by seriwb** [comment]
修正版をリリースしたので、お手数ですがこちらで挙動のご確認をお願いします。
https://github.com/seriwb/reins/releases/tag/0.3.5

おそらく半年は大丈夫かと思いますが、データが増えすぎると同様の事象が発生する可能性があるため、必要に応じて別途対応させてもらいます。

**Comment by denkakka** [comment]
修正版をリリースしたので、お手数ですがこちらで挙動のご確認をお願いします。
https://github.com/seriwb/reins/releases/tag/0.3.5

→ご対応ありがとうございます。セットアップしたので、しばらく動かし続けて確認します。

**Comment by denkakka** [comment]
> 修正版をリリースしたので、お手数ですがこちらで挙動のご確認をお願いします。
> https://github.com/seriwb/reins/releases/tag/0.3.5

→ご対応ありがとうございます。セットアップしたので、しばらく動かし続けて確認します。

**Comment by seriwb** [comment]
今更ですが、どうも相変わらずダメっぽいです。
組み込みDBの限界かもしれないので、どうしたものですかね・・・・
