### ISSUE TITLE
質問。リスト変更のreinsの反映, 仕様。

### ISSUE THREAD

**Issue by hushianasan** [seriwb/reins#22]
#### 前置き
こんにちは。
ITに疎いため、技術的にご無礼してしまったら申し訳ありません。

#### 前提条件
* Bat, VBSファイルを使用し、起動時に自動で起動
* reinsを２つ起動している
* Twitter認証済み, OAuth認証済み？
* allow.txtはTwitterListを入力
* config.txtの取得数, Waitの間隔ベースは標準
* Retweetは取得していない
* リストのみ取得している状態

#### 質問
* スクレイピング中にTwitterのリストを追加, 削除。
起動し直す。スクレイピング対象はきちんとreinsに反映されるだろうか？
（例えば、@Nanasiをリストに追加、そのあときちんと@Nanasiはスクレイピング（保存）されるだろうか？）

**Comment by seriwb** [comment]
Hi
新しく追加したユーザは、次回のデータ取得タイミングから取得対象として反映されます。
reinsを起動し続けていたとしても反映されます。

reinsでリスト内の情報（画像リンク）を取得しようとしたタイミングで、Twitter管理のリスト情報を取得するので、
リスト情報がTwitter側のデータストアに反映されていれば（TwitterのAPIが最新を返してくれれば）、
リストに追加・削除した結果がreins側にも反映されます。
（ちなみにタイムラインについても同様です）

余談ですが、リスト自体を新しく追加、または削除した場合は、情報取得のスタート時に反映される作りになっているので、
reins起動時、またはコンソールに以下のメッセージが出たあとの次の情報取得時から新しい情報が反映されます。
```
list check completed. wait 600s until next search.
```

**Comment by hushianasan** [comment]
こんにちは。
なるほど。感謝です。
今後とも愛用させていただきます。
